### ISSUE TITLE
Remove Hamburger Nav from normal site

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Serengeti#100]
Related to #77 and #86, Now that I realize what "hamburger nav" is.

I think we should remove the hamburger nave from the normal site. One of my colleagues asked me where on earth the nav bar had gone, and I think that especially for people new to the site, who don't know that there is a blog, about page, etc, it might be really hard for them to find. 

I'd like to encourage people to reach those other pages, and think having the nav bar visible all the time would do that. Thoughts?

**Comment by chrissnyder** [comment]
Maybe a solution would be to add the word "Menu" next to the hamburger, so we aren't relying on just iconography?

**Comment by brian-c** [comment]
:hamburger: :-1: :exclamation:
