### ISSUE TITLE
All three photos for the zorilla are the same?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Serengeti#102]
Do we have any more photos of a zorilla?

Right now clicking any of the three picture buttons brings up the same photo.

Intentional?

**Comment by aliburchard** [comment]
No, that's the only photo we had at the time. We have three now. (I think these are the only three zorillas we've seen on SS ever): ASG0001kxk, ASG0007fct, ASG000sxkm

**Comment by DarrenMcRoy** [comment]
Can we get those other two added to the interface?

**Comment by aliburchard** [comment]
@alexbfree would you be able to take this on?

**Comment by aweiksnar** [comment]
I replaced two of the duplicates with cropped subjects here: 819ee532a7f01b5a7588637baa981ec64ce30154, It make take a little while for the site to update since those file-names have to stay the same
