### ISSUE TITLE
Images resize themselves in classification interface

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Serengeti#103]
Margaret passed along this comment from a volunteer:
```
DefaultImage1.tiff is how the pics appear when I start to classify. You can see that the middle button below the pic is active. ExpandedImage1.tiff is how they appear if I select the first or third button (in this pic the third button is active). And they always expand when I click "Finish".

ScreenShot1.tiff has a similar problem but because it's a night pic I can't expand it but once I click "Finish" (as I've done in ScreenShot2.tiff) it expands.

As you can see, the difference isn't huge but it can (and does) make the difference between being able to identify an animal or not. I'm using Safari 5.1.10.

```
Images below...

![defaultimage1](https://cloud.githubusercontent.com/assets/6217406/6335955/2fafc950-bb97-11e4-9fd4-da7e8a3fda43.jpg)
![expandedimage1](https://cloud.githubusercontent.com/assets/6217406/6335956/2fb2faa8-bb97-11e4-956c-05e41309aed1.jpg)
![screenshot1](https://cloud.githubusercontent.com/assets/6217406/6335958/2fb71340-bb97-11e4-9195-fac0b811901d.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/6217406/6335957/2fb64b2c-bb97-11e4-981d-e1150a1a89da.jpg)

**Comment by aweiksnar** [comment]
We don't officially offer support for that version of safari. However, I've pushed up a change that I *think* will fix the display issue. Let me know if you hear anything else back from the volunteer. It should be deployed in the next few hours.

**Comment by aliburchard** [comment]
Ah, fair enough. Thanks for the fix!

**Comment by aliburchard** [comment]
@aweiksnar user says " it's sort of fixed! When I get multiple shot pics, all 3 are the same size but when I click "Finish", the pic still expands slightly" but it works just fine on later Safari, so I think this is good!
