### ISSUE TITLE
Typo in warthog description

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Serengeti#107]
In the description for a warthog: "Its tail is **think** with a black tassel."

I actually don't know if we meant "thin" or "thick."

But should be fixed either way. :-)

**Comment by DiomedeaExulans** [comment]
Their tails are thin, per [Exhibit A](http://static.zooniverse.org/www.snapshotserengeti.org/images/animals/warthog-3.jpg)!
