### ISSUE TITLE
Bigger button to CWW (and C&S?)

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Serengeti#114]
Could someone please input a much larger link to Chicago Wildlife Watch ASAP to take advantage of the BBC article?

Maybe also a second one for Chimp & See if people want to do African wildlife specifically?

Thanks!!

**Comment by vrooje** [comment]
Possible text that moves CWW up and adds C&S:



We're done for now, but we still need you:

With your help, we've classified all the data we have so far. Great work!

If you'd like to try a similar project, how about:
[Chicago Wildlife Watch](http://www.chicagowildlifewatch.org) - this works much like Snapshot Serengeti (though with fewer lions), and there are active images awaiting exploration. [Try it now!](http://www.chicagowildlifewatch.org)
[Chimp & See](http://www.chimpandsee.org/) - explore wildlife in the African jungle with photos *and* video. [Try it now!](http://www.chimpandsee.org/)

We've also left some images of the Serengeti active here so you can classify them, even though we already have enough for the science for now. Keep an eye on [the blog](http://blog.snapshotserengeti.org) for updates about the research and to hear when new data is available.

**Comment by alexbfree** [comment]
Great suggestions Brooke, thanks. The suggestion has come up that we should use images/icons in place of the bullets. We would lose the descriptions of the sites, but it's probably worth it.

Possible images to use:

![chimpansee](https://cloud.githubusercontent.com/assets/1473244/8063656/fb547db0-0ecd-11e5-92f8-02a0abd86966.jpg)

![cww](https://cloud.githubusercontent.com/assets/1473244/8063658/fd648de8-0ecd-11e5-9ca7-d7766460ca17.jpg)

I think the latter one may be too illegible at a small size though....

**Comment by alexbfree** [comment]
alternate version that works better at small sizes

![chicago_flag_square_100px](https://cloud.githubusercontent.com/assets/1473244/8087143/19a43f30-0f91-11e5-9fcd-6a487dc043ab.png)
![chicago_flag_square_500px](https://cloud.githubusercontent.com/assets/1473244/8087142/19a29edc-0f91-11e5-8f54-42819e871ee9.png)
