### ISSUE TITLE
Fix link to dissertation

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Serengeti#115]
reposting from hipchat: would someone be able to fix the link to my dissertation on the snapshotserengeti.org/#/authors page? Either to here (http://gradworks.umi.com/36/43/3643700.html) or to the PDF (https://drive.google.com/a/zooniverse.org/file/d/0BxNFAhD71pdXUHdKRDlBRjZEVUE/view?usp=sharing)

**Comment by alexbfree** [comment]
fixed this earlier today, closing.
