### ISSUE TITLE
Subject images don't load in Firefox

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Serengeti#118]
Today the subjects stopped loading in Firefox (see below), the site worked fine yesterday.  The site works fine in Chrome.

![Uploading Screen Shot 2015-06-11 at 11.58.46 AM.png…]()

**Comment by chrissnyder** [comment]
Any console errors?

**Comment by CKrawczyk** [comment]
No errors, just this warning several times:
"This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1."

**Comment by chrissnyder** [comment]
Don't know then. Works OK here with FF38/OSX. Clear cache and trying again?

**Comment by CKrawczyk** [comment]
Clear cache was the first thing I tried, still does not work on my end.  I am also using FF38/OSX.  Although I just noticed the following error on my console:

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://geordi.zooniverse.org/api/events/. (Reason: CORS request failed)."

**Comment by CKrawczyk** [comment]
One of my FF add-ons was causing the problem, restarting in safe mode fixed the problem.  I am closing this issue.
