### ISSUE TITLE
Ugly and useless scrollbar at bottom of species list

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Serengeti#131]
There's an ugly and useless scrollbar that is now appearing at the bottom of the species list. Hopefully an easy fix?

![screenshot](https://cloud.githubusercontent.com/assets/1066340/11630984/efc0972a-9ccd-11e5-955f-d7e187d1358d.png)

**Comment by aliburchard** [comment]
@mkosmala thanks for catching. We should have this deployed in just a minute.

**Comment by alexbfree** [comment]
OK this is now fixed, via #132 . http://www.snapshotserengeti.org/

**Comment by mkosmala** [comment]
Confirmed fixed. Thanks!
