### ISSUE TITLE
Put up "We're all done" sign and reactivate subjects

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Serengeti#133]
Perhaps catching us all off guard since the progress bar was broken, the Lost Season is actually finished and users are unable to classify.(https://cloud.githubusercontent.com/assets/6217406/11711451/721e11c8-9f1e-11e5-9cb2-70ac68babd51.png)

We need to re-activate some subjects and pop up the "We're done for now" sign on the landing page so kids can still make classifications in classrooms etc.

**Comment by alexbfree** [comment]
The "we're done" box is back. Assigning to Adam to handle subject reactivation

**Comment by astopy** [comment]
I've reactivated the lost season and disabled retirement.
