### ISSUE TITLE
Season Progress Bar Broken

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Serengeti#134]
The progress bar on www.snapshotserengeti.org looks as though 0 progress has been made on the lost season, but the season is actually already done: the api status page reports 100% complete and if you go to www.snapshotserengeti.org/#/classify then you only get the "we're done" sign.

Not urgent because of #133, but probably good to figure out why the status bar didn't work before we launch Seasons 9 and 10.

**Comment by alexbfree** [comment]
Just adding a note, the API status page mentioned above is at https://api.zooniverse.org/projects/serengeti/status

**Comment by alexbfree** [comment]
So that we can still see the issue post #133, I added a copy of the production site at www.snapshotserengeti.org/with-bars with bars still enabled. Obviously that Lost Season bar should show 100% complete.

**Comment by eatyourgreens** [comment]
Does the progress bar just show the complete count from this API call?
http://www.snapshotserengeti.org/_ouroboros_api/projects/serengeti
That shows `complete: 0` for the first item in the seasons array.

**Comment by alexbfree** [comment]
Yeah that's because Adam just re-enabled the lost season data with retirement disabled. It was showing the right number previously.

I found the problem anyway, looks like progress bar calculation was deliberately commented out. I've re-enabled it in #135 - but we can't really test it until we have new data. 

Let's leave this ticket open until season 9, and re-test it just prior to S9 launch to be sure.

**Comment by eatyourgreens** [comment]
I think this is actually the block of code that sets up the counts for progress bars: https://github.com/zooniverse/Serengeti/blob/master/app/index.coffee#L62-L74

then the template just loops through the seasons array, calculating `complete/total`
https://github.com/zooniverse/Serengeti/blob/master/app/views/home_page.eco#L23-L34

This is from just a quick skim through the home page code, though.

**Comment by alexbfree** [comment]
As far as I know, all progress bar issues have now been fixed so I am closing this. @aliburchard @eatyourgreens please re-open if I am incorrect!
