### ISSUE TITLE
Update package.json so that wrong npm version will emit warning; then investigate why not Serengeti not working with latest npm.

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Serengeti#149]
I've noticed that in the last month or so (perhaps due to newer npm versions?), `npm install` is not working properly for Serengeti when building locally.

node/npm versions used:
```
$ node --version ; npm --version
v0.10.38
3.5.3
```

`npm install` is leaving the installation incomplete and not installing the zooniverse library, note it is completely absent from the summary at the end of `npm install --verbose`:

```
serengeti@0.0.1 /code/Serengeti
├── es5-shimify@0.0.1 
├─┬ hem@0.1.9 
│ ├── coffee-script@1.3.3 
│ ├─┬ eco@1.1.0-rc-3 
│ │ └── strscan@1.0.1 
│ ├─┬ fast-detective@0.0.2 
│ │ └─┬ burrito@0.2.12 
│ │   └── traverse@0.5.2 
│ ├─┬ optimist@0.2.8 
│ │ └── wordwrap@0.0.3 
│ ├─┬ strata@0.15.1 
│ │ ├── bufferedstream@1.0.2 
│ │ ├── markdown@0.3.1 
│ │ ├── mime@1.2.3 
│ │ ├── strftime@0.4.6 
│ │ └── usererror@1.0.2 
│ ├─┬ stylus@0.22.6 
│ │ ├── cssom@0.2.1 
│ │ ├── growl@1.1.0 
│ │ └── mkdirp@0.0.7 
│ ├── uglify-js@1.1.1 
│ └── watch@0.4.0 
├── jqueryify@1.8.0 
├── json2ify@0.0.1 
├── moment@1.7.2 
├── nib@0.8.2 
├─┬ publisssh@0.1.3 
│ ├── async@0.2.10 
│ ├─┬ aws-sdk@1.3.2 
│ │ ├─┬ xml2js@0.2.4 
│ │ │ └── sax@1.2.1 
│ │ └─┬ xmlbuilder@7.0.0 
│ │   └── lodash@4.6.1 
│ ├── coffee-script@1.4.0 
│ ├── colors@0.6.2 
│ ├── mime@1.2.11 
│ ├── optimist@0.3.7 
│ └── wrench@1.4.4 
├─┬ serveup@0.0.5 
│ └─┬ express@2.5.0 
│   ├── connect@1.7.3 
│   └── qs@6.1.0 
├── spine@1.0.7 
├── t7e@0.2.3 
├── underscore@1.4.2 
├── zooniverse-geordi-client@1.3.6 
├── zooniverse-user-string-getter@1.1.22 
└── zootorial@0.2.4 
```
After this, `npm start` will work, but the first page access will crash the app.

In order to get Serengeti working you have to type an additional
```
npm install zooniverse/Zooniverse#98ffd4b
```
(as specified in package.json)

which gives
```
serengeti@0.0.1 /code/Serengeti
├── hem@0.1.9
└── Zooniverse@0.0.1  extraneous (git://github.com/zooniverse/Zooniverse.git#98ffd4bf4e161f1ce64d377a640222697610a261)
```
After this, the app works ok when you `npm start` it.

It seems that for some reason it thinks the Zooniverse library dependency is extraneous and so doesn't obey package.json's request to install that dependency.

For some reason this is not proving an issue on staging or production (maybe old npm being used there?), but I feel like that is only a matter of time. Does anyone know why this might be happening? Anyone have a fix?

**Comment by alexbfree** [comment]
@brian-c @parrish any thoughts?

**Comment by brian-c** [comment]
Try npm 2.x. npm 3 made some big changes.

**Comment by alexbfree** [comment]
Thanks. 

It wouldn’t surprise me if you are correct, since npm is the only part of the equation that has changed, i had already theorised that the new npm versions were causing the problem. But my question is less "how do I avoid having to do this" and more "what is going on and how do we fix this so that it *doesn't* break on latest npm?" It seems to me it's probably only a matter of time until npm gets updated on production/staging machines and suddenly we have a broken install on production/staging. Seems like we should fix this so it will work on latest npm. But I don't know node/npm well enough to figure out what is going on here.

**Comment by brian-c** [comment]
I'm not sure, I'm not seeing any errors in what you posted. npm 2.x is the LTS version, so it's safe to stick with until next year. I recommend setting the `engines` property in package.json (see PFE's for an example), which I think'll throw a warning if you use an off-version. As far as upgrading goes, that'll need some research to see what's changed.

**Comment by alexbfree** [comment]
In case it helps, I'm attaching my logs to this ticket [verbose-install-logs.zip](https://github.com/zooniverse/Serengeti/files/188165/verbose-install-logs.zip)

Good idea about marking the  `npm`/`node` versions in the engines directive, that should at least protect us against accidentally breaking production should `npm` get upgraded. I'll need to switch from `n` to `nvm` so i can nail down the last known good `npm` version.

We should research this further... once i have updated the engines directive i will leave this ticket open as a reminder.

**Comment by rogerhutchings** [comment]
It's worth mentioning that the `engines` property only gets respected during an install. If you're switching versions a lot, you could add [check-engines](https://www.npmjs.com/package/check-engines) to each item in the `scripts` block

**Comment by alexbfree** [comment]
@rogerhutchings when you say "during an install", you mean during a run of `npm install` right?

If so I think that's fine, my main concern here is to ensure production/staging don't accidentally break if we change the npm version.

**Comment by rogerhutchings** [comment]
yeah. you might want to also set `engineStrict: true` as well if it'll actually break things, it only warns by default
