### ISSUE TITLE
Updates to the team page

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Serengeti#153]
Update Margaret's bio to:

Margaret is an ecologist who earned her Ph.D. at the University of Minnesota and is now a researcher at Harvard University. She explores how plant and animal species and ecosystems change over time. In addition to Snapshot Serengeti, she is involved with Zooniverse projects Season Spotter and Jungle Rhythms.

Update my bio to:
Ali is an ecologist who earned her Ph.D. at the University of Minnesota. She initiated the camera trapping survey in 2010 for her dissertation research on how Serengeti carnivores coexist. When not  trying to foil the relentless efforts of hyenas and elephants to munch and destroy the cameras, she actually managed to do some science! After her PhD, she spent two years at the Zooniverse working to build citizen science projects for ecology. She is now a AAAS fellow working on environmental policy at the US Department of State, but still enjoys working with Snapshot Serengeti data when she can.

And please add two new researchers (photos attached):
![img_2081_small](https://cloud.githubusercontent.com/assets/6217406/20399887/b2e75704-acc0-11e6-8f27-db604d8f49da.jpg)
![morrisoncloseup](https://cloud.githubusercontent.com/assets/6217406/20399889/b32a70b6-acc0-11e6-9348-b60c0796a7d2.jpg)

Michael Anderson
Michael is an Associate Professor of Biology & Endowed Chair in Environmental Resources at Wake Forest University. Michael has been conducting research in Serengeti since 2000, where he has been studying plants, herbivores and how to fix a land-rover with nothing but a leatherman. He is particularly interested in how interactions among large herbivores and their predators can influence savanna dynamics. Michael is thrilled to be part of the Snapshot Serengeti and is happy to be working with such a great team of collaborators.

Tom Morrison
Tom is a postdoc research associate in the Institute of Biodiversity, Animal Health and Comparative Medicine at the University of Glasgow in Scotland. With a background in population demography, Tom’s work addresses the practical aspects of wildlife management and conservation, particularly in Tanzania. He spent 2 years living in Serengeti National Park as a postdoc of Michael Anderson at Wake Forest University on a project to understand changes in tree cover in savannas.

**Comment by hrspiers** [comment]
Hi, 
This has been updated,
Helen
