### ISSUE TITLE
Subjects duplicated in Talk collection

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Serengeti#67]
When I collect a subject it is shown twice in my collection.

**Comment by mrniaboc** [comment]
This problem still exists!

**Comment by aliburchard** [comment]
This is still happening. Not using the heart button from the classification interface, but whenever I add a subject into a collection directly from talk.

**Comment by chrissnyder** [comment]
Moving this to https://github.com/zooniverse/Talk/issues/136
