### ISSUE TITLE
Add tracking URLs to landing page

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Serengeti#73]
Can someone please change the redirection links to Cyclone Center, Bat Detective, and Zoo Home on Serengeti landing page to the following trackable links so we can see how many people are clicking them:

http://www.cyclonecenter.org/?utm_source=Redirect&utm_medium=Link&utm_campaign=Serengeti

http://www.batdetective.org/?utm_source=Redirect&utm_medium=Link&utm_campaign=Serengeti

http://www.zooniverse.org/?utm_source=Redirect&utm_medium=Link&utm_campaign=Serengeti

**Comment by chrissnyder** [comment]
Looks to be deployed.
