### ISSUE TITLE
You can fall out of the tutorial

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Serengeti#74]
I noticed that it is quite easy to fall out of the tutorial, and be left in a "not quite sure if I'm done" state (only to have to go back to the homepage and start the tutorial all over again).

You can replicate this by either doing something that isn't the thing the tutorial instructs you to do, at any stage, or by too quickly doing the next thing before the instruction popup appears. I think it might have been something to do with whether or not you click on the instruction balloon too.

We should investigate this anyway.

**Comment by chrissnyder** [comment]
This is an accepted part, for better or worse, of how we present the tutorial. Other projects that use the same style tutorial fall victim to the same class of problems.

That said, I don't think anyone is ever going to revise the Serengeti tutorial code enough to have this not occur so I'm closing this. If someone feels the urge otherwise, of course feel free to re-open and self-assign.

**Comment by alexbfree** [comment]
OK. just adding a note for future consideration:
I think the easy way to fix this is to have an indication on screen when you are in tutorial mode, such as a banner or something, and within that banner to have an "exit tutorial" button. That way even if the balloons get lost and you fall out, you can still exit the tutorial properly (at the moment the only workaround is to reload the page).

**Comment by alexbfree** [comment]
I was just demonstrating Snapshot Serengeti to a friend and this became a real annoyance for her as a first time user. For one thing, if you've already been introduced to the app, you want to get through the tutorial as quickly as possible. A skip tutorial button would be useful. Also, if you're already partly familar, or just not inclined to read all the text, it is very easy to click away the popups and not know what to do next. We should consider an exit tutorial button or at least a way to resume the tutorial, because it's far too easy to get left in a non-tutorial state. 

I am not re-opening this for now, but I will have a look at it when I have some time.
