### ISSUE TITLE
Serengeti Mobile designs

### ISSUE THREAD

**Issue by heathv** [zooniverse/Serengeti#77]
Various screenshots below for Serengeti Mobile. Essentially some stuff is shuffled around a bit and buttons are bigger. 

![serengeti-mobile-animate](https://cloud.githubusercontent.com/assets/4551411/5944350/e57a6d0a-a6eb-11e4-9b77-90db0aab7f14.gif)

![serengeti-mobile-animaldetail](https://cloud.githubusercontent.com/assets/4551411/5944292/5bcd1b0c-a6eb-11e4-98ca-069b3579fa7a.jpg)
![serengeti-mobile-menu](https://cloud.githubusercontent.com/assets/4551411/5944293/5bcfdd6a-a6eb-11e4-8d12-831198ecc99c.jpg)
![serengeti-mobile](https://cloud.githubusercontent.com/assets/4551411/5944294/5bd111ee-a6eb-11e4-958d-d719a0aa58dd.jpg)

**Comment by aweiksnar** [comment]
Sweet, looks great. The "Snapshot Serengeti" site title is an image, so I may need a stacked version or replacement font specs for that

**Comment by heathv** [comment]
[Here is the link to the file on Extract](http://adobe.ly/1DhuDDe) and I'll have to email you the .svg since github doesn't like those.

**Comment by aweiksnar** [comment]
Cool, thanks!

**Comment by aliburchard** [comment]
Can i just say that this is so freakin cool?
