### ISSUE TITLE
On master branch, screen corrupts at low image sizes (responsiveness not working)

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Serengeti#91]
At 400 pixels, signout button is under zoo tab accessible, main image is cropped, finish and other buttons are inaccessible. animal selection and favorite button inaccessible.
![400px](https://cloud.githubusercontent.com/assets/1473244/6078229/dc9cbd14-adee-11e4-9556-8f12dc159068.png)

At 565 pixels, main image is cropped and bottom buttons are badly spaced. animal selection and favorite button inaccessible.
![565px](https://cloud.githubusercontent.com/assets/1473244/6078231/dc9ede46-adee-11e4-8de1-0ffc7b81a1ee.png)

At 965 pixels, animal selector panel & clear filters button are cropped, zoo top bar text appears over the page. Buttons below image are pulled to the left and unequally spaced vertically.
![965px](https://cloud.githubusercontent.com/assets/1473244/6078230/dc9eb718-adee-11e4-9b40-0d780e6ecd70.png)

I imagine this may just be a merge problem, @aweiksnar or @chrissnyder can you investigate?

**Comment by camallen** [comment]
Looks like the `zooniverse-top-bar` isn't very responsive. Most likely a CSS fix.

**Comment by aweiksnar** [comment]
@alexbfree I'm believing this #92 to be local issues. Try deleting your `node_modules` folder and doing a fresh `npm  install`. I tested out a fresh clone/install/deploy-to-demo and all seems good for me. The latest master branch should resemble the designs in #77 (also currently on demo/serengeti)

Let me know if that doesn't remedy the issue and maybe we can chat more about it today

**Comment by alexbfree** [comment]
Seems to have been a local npm sync issue, a fresh clone resolves it. Closing.
