### ISSUE TITLE
"Confused with" images are wrong

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Serengeti#95]
The "confused with" photo for cattle is of a baboon, and the "confused with" photo for steenbok is of an aardwolf. (This is the photo that appears if you click "often confused with" on another animal's page.)

Also, the "confused with" photo for a duiker may or may not be a duiker, but if it is, we could probably choose a better duiker picture.

(Source; I've verified that this is indeed a bug: http://talk.snapshotserengeti.org/#/boards/BSG0000002/discussions/DSG00010nt?page=1&comment_id=54da51396975260914000221)

**Comment by aliburchard** [comment]
Gah, thanks Darren. Weirdly, these previously linked to the correct images. HOpefully we'll get it sorted soon. Cheers.

**Comment by chrissnyder** [comment]
Maybe I'm not seeing something, but it looks correct now? Did someone deploy a fix or am I just not looking at the right thing?

**Comment by aweiksnar** [comment]
Yeah looks to be good for me as well

**Comment by DarrenMcRoy** [comment]
Looks good for me, too. I'll leave this open until I'm 100% sure that it's fixed. It may have just been a processing delay.

**Comment by brian-c** [comment]
Still looks off to me. I just cleared the proxy cache, so it's not that.

![screen shot 2015-02-11 at 8 16 31 am](https://cloud.githubusercontent.com/assets/464389/6143798/8a243824-b1c6-11e4-9a9d-f5bcf5a747b7.png)

![screen shot 2015-02-11 at 8 19 03 am](https://cloud.githubusercontent.com/assets/464389/6143808/aed8fc22-b1c6-11e4-8e7a-2cec5eeb5757.png)

I think these thumbnails are kept by a big long sprite. Might just be out of order.

**Comment by chrissnyder** [comment]
I added some to the sprite when I added the new species, but I tacked them onto the bottom.

In an incognito window, with the proxy cache freshly cleared, it shows correctly. I have to imagine this is a caching issue somewhere along the line.

![](http://i.imgur.com/RB9tmYk.png)

**Comment by brian-c** [comment]
Right you are. Is it worth changing the image file name to make sure?

**Comment by chrissnyder** [comment]
I think so, especially with S8 going out now.
