### ISSUE TITLE
"Animate" with mouse scroll button

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Serengeti#96]
A requested feature from a volunteer:

> It would save time if the user could move between the 3 frames by interacting with the little selection circles via the scroll wheel, so that you don’t have to take your eyes from the frames, especially when looking for animals in the bushes or in the distance. Maybe something can be done with an AutoHotkey script.

**Comment by aweiksnar** [comment]
Frames can be selected via the keyboard by pressing 1,2 and 3 to select a frame, or space-bar to toggle play/pause. I think this accomplishes the same goal that the volunteer is asking for.
