### ISSUE TITLE
"Discuss" button opens a new tab

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Serengeti#97]
Did we intentionally make the "discuss" button open in a new tab?

Users aren't big fans of it... Thoughts?

http://talk.snapshotserengeti.org/#/boards/BSG0000002/discussions/DSG00010s7?page=1&comment_id=54dba8856975261406000061

**Comment by aweiksnar** [comment]
There was a discussion about this here: https://github.com/zooniverse/Serengeti/issues/81. Very easy to change back if users aren't happy about it

**Comment by eatyourgreens** [comment]
If you want to prevent multiple new tabs opening, use a named target on the
link eg target=talk instead of target=_blank Then Talk will always open in
the same tab it opened in previously.

Jim

On Thursday, February 12, 2015, Alex Weiksnar <notifications@github.com>
wrote:

> There was a discussion about this here: #81
> <https://github.com/zooniverse/Serengeti/issues/81>. Very easy to change
> back if users aren't happy about it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Serengeti/issues/97#issuecomment-74090412>.
>


-- 
--
James O'Donnell
email: jim@zooniverse.org
mobile: 07811 771 352
twitter: @pekingspring

**Comment by aweiksnar** [comment]
@eatyourgreens's solution sounds like it will please the users who like to classify in multiple tabs. I'll add that in, and then if people are still wishing for a full page-change to talk we can make switch back to the pre-season8 style

**Comment by eatyourgreens** [comment]
Looks like I used that technique in the OWD classifier too (on the Talk links in the comments popup) https://github.com/zooniverse/Diaries/blob/master/app/views/classifier/comments.eco Probably to solve the same issue there.

**Comment by aliburchard** [comment]
Hmm, I personally like when "discuss" opens a new tab (separate from the classifying window), but it would probably be best if hitting "discuss" routed to the *same* new tab instead of opening a second new tab. I *think* that's what @eatyourgreens is suggesting? And I like it.

**Comment by DarrenMcRoy** [comment]
I would be up for that functionality, but tell me... what happens if you go into Talk, open a new tab, then from that tab, hit "return to classifying," classify something, and then hit "discuss" again?

Won't you still end up spawning more and more tabs?

**Comment by eatyourgreens** [comment]
http://operationwardiary.org opens Talk in a new tab, so maybe try that to see how it works? What I'm suggesting here is the code that I used on OWD.

**Comment by aweiksnar** [comment]
The aforementioned open-talk-in-same-new-tab behavior should be deployed (2ee41a36aff75ed58f286296d67b4026becaa3e4). It seems like production updates are taking a while to occur, as seen with the 'often confused with' image .
